backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "menu"
    label: "Menu"
    files:
      - name: "sauces"
        label: "Sauces"
        file: "src/content/_menu/sauce_list.yml"
        fields:
          - {name: "title", Label: "Title", widget: "string"}
          - {name: "price", label: "Price", widget: "number", value_type: "float", min: 0, step: 0.1}
          - name: "items"
            label: "Sauce"
            widget: "list"
            fields:
              - {name: "title", Label: "Title", widget: "string"}
      - name: "entrees"
        label: "Entrees"
        file: "src/content/_menu/entrees.yml"
        fields:
          - {name: "title", Label: "Title", widget: "string"}
          - name: "items"
            label: "Entree"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text", required: false}
              - {label: "Price", name: "price", widget: "number", value_type: "float", min: 0, step: 0.5}
      - name: "sides"
        label: "Sides"
        file: "src/content/_menu/sides.yml"
        fields:
          - {name: "title", Label: "Title", widget: "string"}
          - name: "items"
            label: "Side"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text", required: false}
              - {label: "Price", name: "price", widget: "number", value_type: "float", min: 0, step: 0.5}
      - name: "addons"
        label: "Add-Ons"
        file: "src/content/_menu/addons.yml"
        fields:
          - {name: "title", Label: "Title", widget: "string"}
          - name: "items"
            label: "Add-On"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text", required: false}
              - {label: "Price", name: "price", widget: "number", value_type: "float", min: 0, step: 0.5}
      - name: "drinks"
        label: "Drinks"
        file: "src/content/_menu/drinks.yml"
        fields:
          - {name: "title", Label: "Title", widget: "string"}
          - name: "items"
            label: "Drink"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Price", name: "price", widget: "number", value_type: "float", min: 0, step: 0.5}
  - name: "specials"
    label: "Specials"
    folder: "src/content/_menu/specials"
    create: true
    sortable_fields: ['startDate', 'endDate', 'title', 'price']
    summary: "{{fields.title}}, {{fields.startDate}} - {{fields.endDate}}"
    format: yml
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "body", widget: "text"}
      - {label: "Price", name: "price", widget: "number", value_type: "float", min: 0, step: 1}
      - {label: "Start Date", name: "startDate", widget: "datetime", date_format: "MM/DD/YYYY", format: "YYYY-MM-DD", time_format: false, picker_utc: true}
      - {label: "End Date", name: "endDate", widget: "datetime", date_format: "MM/DD/YYYY", format: "YYYY-MM-DD", time_format: false, picker_utc: true}
      - {label: "Image", name: "image", widget: "image", media_folder: "/static/img"}